
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/cookie-persistence: ServerLNB
    ingress.class: haproxy
    haproxy-ingress.github.io/balance-algorithm: roundrobin
    haproxy-ingress.github.io/blue-green-deploy: group=blue=1,group=green=1
    haproxy-ingress.github.io/blue-green-mode: pod
    haproxy.org/src-ip-header: "True-Client-IP"
    haproxy.org/backend-config-snippet: |
      use_backend default if { path -i -m  /evil/ } || { path -i -m end /evil }
      http-request redirect location https://google.com if { path -i -m beg /evil/ } || { path -i -m end /evil }
    #haproxy.org/path-rewrite: "/"
  name: nginx-lnb-api
spec:
  ingressClassName: haproxy
  rules:
  - host: api.viaf.pp.ua
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 5000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - api.viaf.pp.ua
    secretName: api.viaf.pp.ua
