apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  Kind: Ingress
  metadata:
    annotations:
      haproxy.org/cookie-persistence: ServerLNB
      ingress.class: haproxy
    name: argocd-ingress
  spec:
    ingressClassName: haproxy
    rules:
    - host: svc.viaf.pp.ua
      http:
        paths:
        - backend:
            service:
              name: nginx
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - svc.viaf.pp.ua
      secretName: svc.viaf.pp.ua
