apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "700m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: index1-html
            mountPath: "/usr/share/nginx/html"
            subPath: index1.html
          - name: nginx-conf
            mountPath: "/etc/nginx/"
            subPath: nginx.conf

      volumes:
        - name: index1-html
          configMap:
              name: index1.html
        - name: nginx-conf
          configMap:
            name: nginx.conf
